[package]
name = "rube-voxel"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
bzip2 = "0.6.1"
glam = "0.30.9"
postcard = { version = "1.1.3", features = ["alloc"] }
serde = { version = "1.0.228", features = ["derive"] }
